name: Install on Mac

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        ocaml-compiler:
          - "5.2"
          - "4.14"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-local-packages: |
            *.opam
          dune-cache: true
          allow-prerelease-opam: true

      - name: macos fix
        run: |
          brew update
          brew upgrade
          brew install pkgconf
        # work around https://github.com/actions/runner-images/issues/10984

      - name: Owl Deps
        run: brew install aspcud openblas lapack

      - name: Initialize OPAM
        run: opam init --disable-sandboxing --yes

      - name: Create and Set OPAM Switch
        run: |
          opam switch create owl-switch 5.1.0
          eval $(opam env)  # Load the new switch
      
      #- name: Clone owl
      #  run: git clone https://github.com/owlbarn/owl.git /tmp/owl
      
      #- name: Owl OCaml Deps
      #  run: |
      #    cd /tmp/owl  
      #    opam install ocaml-compiler-libs alcotest ctypes dune-configurator stdio npy odoc 
      # # conf-openblas
      
      - name: Install owl
        #run: |
        #  cd /tmp/owl
        #  opam exec -- dune build @install 
        #  eval $(opam env)
        run : opam install owl 
        
      - name: Install owl-plplot deps 
        run: opam install plplot # owl # install owl is a temp hack to the error in finding the installed version
      

      - name: Install owl-plplot
        run: opam exec -- dune build @install 

      - name: Run tests
        run: opam exec -- dune build
        working-directory: examples
          